### ISSUE TITLE
Keybindings stopped working.

### ISSUE THREAD

**Issue by Rakreo** [Bestride/BeStride#247]
### WoW Version

Retail (9.2.5)

### Bestride Version

2.0.12

### Steps to Reproduce

1. Assign a key for "Mounting"
2. Press "Assigned Key"

### Observed Behavior

No errors in BugSack/!BugGrabber.

Deleted WTF and Addon Folder. Installed BeStride by itself. Tried assigning multiple keys......

**Comment by smccandl** [comment]
Found some new information....  Somehow a cVar was set, not sure what one or what value it was changed to but after running "/console cvar_default" everything is fine....  Weird. Thought is was the addon because the same problem existed on my laptop that didn't have Warcraft on it. After installing Warcraft the "Keybind" issue still showed up. It was only after my wife logged into my laptop did I realize that her account worked fine. If I ever figure out what cVar it was I will try and remember to update here.

**Comment by DanSheps** [comment]
Thanks for the update @Rakreo
